name: ci

on:
  push:
#    branches:
#      - 'master'
    tags:
      - "v*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - 
        name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}
      - 
        name: Check out GitHub repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: chamlinghelen/nginx-app

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{GITHUB_SHA::10}}
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ github.repository }}:${{ env.RELEASE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
